name: heatherlauren.me
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: blog/:title/
collections:
  portfolio_posts:
    output: true
    permalink: /portfolio/:title/
